@startuml
title DeviceService Component Diagram

top to bottom direction

!includeurl ../templates/C4_Component.puml

System_Ext(hubs, "Smart Home Hubs", "Hub to interact with devices in home")

Container_Boundary(WarmHouseSystem, "WarmHouse System") {
  Container(DeviceService, "Device Service", "Java, Spring", "Add, configure, control and show state of devices")
  ContainerDb(Database, "Database", "MongoDb", "Stores user data and devices data")
  ContainerQueue(Kafka, "Kafka", "Kafka", "Events from devices")
}

Container(DeviceService, "Device Service", "Java, Spring", "Add, configure, control and show state of devices") {
  Component(HubController, "HubController", "Register and manage hub")
  Component(DeviceController, "DeviceController", "Register and manage device")
  Component(ServiceLayer, "ServiceLayer", "Business Logic")
  Component(RepositoryLayer, "RepositoryLayer", "Data access logic")
}

Rel(HubController,ServiceLayer,"Calls business logic")
Rel(DeviceController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,RepositoryLayer,"Reads/Writes data")
Rel(ServiceLayer,hubs,"Manage hubs")
Rel(RepositoryLayer,Database,"Reads/Writes devices data")
Rel(Kafka,ServiceLayer,"Events from devices")



@enduml