@startuml
title UserProfileService Component Diagram

top to bottom direction

!includeurl ../templates/C4_Component.puml

Container_Boundary(WarmHouseSystem, "WarmHouse System") {
  Container(UserProfileService, "UserProfileService", "Java, Spring", "Registration and managing profile")
  ContainerDb(Database, "Database", "PostgreSQL", "Stores user data")
}

Container(UserProfileService, "UserProfileService", "Java, Spring", "Registration and managing profile") {
  Component(UserProfileController, "UserProfileController", "Registration and managing profile")
  Component(ServiceLayer, "ServiceLayer", "Business Logic")
  Component(RepositoryLayer, "RepositoryLayer", "Data access logic")
}

Rel(UserProfileController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,RepositoryLayer,"Reads/Writes data")
Rel(RepositoryLayer,Database,"Reads/Writes user data")
@enduml