@startuml
title FitLife Membership Management Code Diagram

top to bottom direction

!includeurl ../templates/C4_Component.puml

class User {
  +String name
  +String email
  +List<House> houses
  +void register()
  +void login()
}

class House {
  +UUID id
  +String address
}

class Device {
  +UUID id
  +DeviceType type_id
  +House house_id
  +String serial_number
  +Boolean status
  +void register()
  +void activate()
  +void disable()
  +void function()
  +TelemetryData getState()
}

class TelemetryData {
  +DateTime timestamp
  +String data
}

User "1" -- "0..*" House : has
House "1" -- "1..*" Device : has
Device "1" -- "1..*" TelemetryData : includes

@enduml